config/routes.rb
Myapp::Application.routes.draw do

  resources :electorates
  resources :members
  resources :hansards
  resources :postcodes,         :controller => "postcode_lookups"
  match "party/:id" => "members#party"
  








  root :to => 'postcode_lookups#index'


end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/cons_info.rb
class ConsInfo < ActiveRecord::Base
end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
end

app/models/electorate.rb
class Electorate < ActiveRecord::Base
  has_many    :members,   :primary_key => 'title', :foreign_key => 'constituency'
end

app/models/ep_object.rb
class EpObject < ActiveRecord::Base
end

app/models/gid_redirect.rb
class GidRedirect < ActiveRecord::Base
end

app/models/hansard.rb
class Hansard < ActiveRecord::Base
  belongs_to :epobject_id
  belongs_to :speaker_id
end

app/models/index_batch.rb
class IndexBatch < ActiveRecord::Base
end

app/models/m_office.rb
class MOffice < ActiveRecord::Base
  belongs_to :person
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many    :speeches,    :primary_key => 'aphkey',       :foreign_key => 'member_id',    :order => 'date DESC'
  has_many    :electorates, :primary_key => 'constituency', :foreign_key => 'title'
  has_many    :postcodes,   :through => :electorate

  default_scope :order => 'last_name ASC'
end

app/models/member_info.rb
class MemberInfo < ActiveRecord::Base
  belongs_to :member
end

app/models/party.rb
class Party < ActiveRecord::Base
end

app/models/pbc_member.rb
class PbcMember < ActiveRecord::Base
  belongs_to :member
  belongs_to :bill
end

app/models/person_info.rb
class PersonInfo < ActiveRecord::Base
  belongs_to :person
end

app/models/postcode_lookup.rb
class PostcodeLookup < ActiveRecord::Base
end

app/models/speech.rb
class Speech < ActiveRecord::Base
  belongs_to  :member,    :primary_key => 'member_id',       :foreign_key => 'aphkey'
  default_scope :order => 'date DESC'
end

app/models/title.rb
class Title < ActiveRecord::Base
end

app/controllers/hansards_controller.rb
class HansardsController < ApplicationController
  # GET /hansards
  # GET /hansards.json
  def index
    @hansards = Hansard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hansards }
    end
  end

  # GET /hansards/1
  # GET /hansards/1.json
  def show
    @hansard = Hansard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hansard }
    end
  end

  # GET /hansards/new
  # GET /hansards/new.json
  def new
    @hansard = Hansard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hansard }
    end
  end

  # GET /hansards/1/edit
  def edit
    @hansard = Hansard.find(params[:id])
  end

  # POST /hansards
  # POST /hansards.json
  def create
    @hansard = Hansard.new(params[:hansard])

    respond_to do |format|
      if @hansard.save
        format.html { redirect_to @hansard, notice: 'Hansard was successfully created.' }
        format.json { render json: @hansard, status: :created, location: @hansard }
      else
        format.html { render action: "new" }
        format.json { render json: @hansard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hansards/1
  # PUT /hansards/1.json
  def update
    @hansard = Hansard.find(params[:id])

    respond_to do |format|
      if @hansard.update_attributes(params[:hansard])
        format.html { redirect_to @hansard, notice: 'Hansard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hansard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hansards/1
  # DELETE /hansards/1.json
  def destroy
    @hansard = Hansard.find(params[:id])
    @hansard.destroy

    respond_to do |format|
      format.html { redirect_to hansards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/cons_info_helper.rb
module ConsInfoHelper
end

app/helpers/hansards_helper.rb
module HansardsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/hansards/_form.html.haml
= form_for @hansard do |f|
  -if @hansard.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hansard.errors.count, "error")} prohibited this hansard from being saved:"
      %ul
        - @hansard.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :epobject_id
    = f.text_field :epobject_id
  .field
    = f.label :git
    = f.text_field :git
  .field
    = f.label :htype
    = f.number_field :htype
  .field
    = f.label :speaker_id
    = f.text_field :speaker_id
  .field
    = f.label :major
    = f.number_field :major
  .field
    = f.label :section_id
    = f.number_field :section_id
  .field
    = f.label :subsection_id
    = f.number_field :subsection_id
  .field
    = f.label :hpos
    = f.number_field :hpos
  .field
    = f.label :hdate
    = f.date_select :hdate
  .field
    = f.label :htime
    = f.time_select :htime
  .field
    = f.label :source_url
    = f.text_field :source_url
  .field
    = f.label :minor
    = f.number_field :minor
  .actions
    = f.submit 'Save'

app/views/hansards/edit.html.haml
%h1 Editing hansard

= render 'form'

= link_to 'Show', @hansard
\|
= link_to 'Back', hansards_path

app/views/hansards/index.html.haml
%h1 Listing hansards

%table
  %tr
    %th Epobject
    %th Git
    %th Htype
    %th Speaker
    %th Major
    %th Section
    %th Subsection
    %th Hpos
    %th Hdate
    %th Htime
    %th Source url
    %th Minor
    %th
    %th
    %th

  - @hansards.each do |hansard|
    %tr
      %td= hansard.epobject_id
      %td= hansard.git
      %td= hansard.htype
      %td= hansard.speaker_id
      %td= hansard.major
      %td= hansard.section_id
      %td= hansard.subsection_id
      %td= hansard.hpos
      %td= hansard.hdate
      %td= hansard.htime
      %td= hansard.source_url
      %td= hansard.minor
      %td= link_to 'Show', hansard
      %td= link_to 'Edit', edit_hansard_path(hansard)
      %td= link_to 'Destroy', hansard, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Hansard', new_hansard_path

app/views/hansards/new.html.haml
%h1 New hansard

= render 'form'

= link_to 'Back', hansards_path

app/views/hansards/show.html.haml
%p#notice= notice

%p
  %b Epobject:
  = @hansard.epobject_id
%p
  %b Git:
  = @hansard.git
%p
  %b Htype:
  = @hansard.htype
%p
  %b Speaker:
  = @hansard.speaker_id
%p
  %b Major:
  = @hansard.major
%p
  %b Section:
  = @hansard.section_id
%p
  %b Subsection:
  = @hansard.subsection_id
%p
  %b Hpos:
  = @hansard.hpos
%p
  %b Hdate:
  = @hansard.hdate
%p
  %b Htime:
  = @hansard.htime
%p
  %b Source url:
  = @hansard.source_url
%p
  %b Minor:
  = @hansard.minor

= link_to 'Edit', edit_hansard_path(@hansard)
\|
= link_to 'Back', hansards_path