config/routes.rb
Myapp::Application.routes.draw do

  resources :electorates
  resources :members
  resources :hansards
  resources :postcodes,         :controller => "postcode_lookups"
  match "party/:id" => "members#party"
  








  root :to => 'postcode_lookups#index'


end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/cons_info.rb
class ConsInfo < ActiveRecord::Base
end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
end

app/models/electorate.rb
class Electorate < ActiveRecord::Base
  has_many    :members,   :primary_key => 'title', :foreign_key => 'constituency'
end

app/models/ep_object.rb
class EpObject < ActiveRecord::Base
end

app/models/gid_redirect.rb
class GidRedirect < ActiveRecord::Base
end

app/models/hansard.rb
class Hansard < ActiveRecord::Base
  belongs_to :epobject_id
  belongs_to :speaker_id
end

app/models/index_batch.rb
class IndexBatch < ActiveRecord::Base
end

app/models/m_office.rb
class MOffice < ActiveRecord::Base
  belongs_to :person
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many    :speeches,    :primary_key => 'aphkey',       :foreign_key => 'member_id',    :order => 'date DESC'
  has_many    :electorates, :primary_key => 'constituency', :foreign_key => 'title'
  has_many    :postcodes,   :through => :electorate

  default_scope :order => 'last_name ASC'
end

app/models/member_info.rb
class MemberInfo < ActiveRecord::Base
  belongs_to :member
end

app/models/party.rb
class Party < ActiveRecord::Base
end

app/models/pbc_member.rb
class PbcMember < ActiveRecord::Base
  belongs_to :member
  belongs_to :bill
end

app/models/person_info.rb
class PersonInfo < ActiveRecord::Base
  belongs_to :person
end

app/models/postcode_lookup.rb
class PostcodeLookup < ActiveRecord::Base
end

app/models/speech.rb
class Speech < ActiveRecord::Base
  belongs_to  :member,    :primary_key => 'member_id',       :foreign_key => 'aphkey'
  default_scope :order => 'date DESC'
end

app/models/title.rb
class Title < ActiveRecord::Base
end

app/controllers/electorates_controller.rb
class ElectoratesController < ApplicationController
  # GET /electorates
  # GET /electorates.json
  def index
    @electorates = Electorate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @electorates }
    end
  end

  # GET /electorates/1
  # GET /electorates/1.json
  def show
    @electorate = Electorate.find_by_title(params[:id])
    @members = Member.find_all_by_constituency(@electorate.title)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @electorate }
    end
  end

  # GET /electorates/new
  # GET /electorates/new.json
  def new
    @electorate = Electorate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @electorate }
    end
  end

  # GET /electorates/1/edit
  def edit
    @electorate = Electorate.find(params[:id])
  end

  # POST /electorates
  # POST /electorates.json
  def create
    @electorate = Electorate.new(params[:electorate])

    respond_to do |format|
      if @electorate.save
        format.html { redirect_to @electorate, notice: 'Electorate was successfully created.' }
        format.json { render json: @electorate, status: :created, location: @electorate }
      else
        format.html { render action: "new" }
        format.json { render json: @electorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /electorates/1
  # PUT /electorates/1.json
  def update
    @electorate = Electorate.find(params[:id])

    respond_to do |format|
      if @electorate.update_attributes(params[:electorate])
        format.html { redirect_to @electorate, notice: 'Electorate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @electorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electorates/1
  # DELETE /electorates/1.json
  def destroy
    @electorate = Electorate.find(params[:id])
    @electorate.destroy

    respond_to do |format|
      format.html { redirect_to electorates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/electorates_helper.rb
module ElectoratesHelper
end

app/helpers/hansards_helper.rb
module HansardsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/electorates/_form.html.haml
= form_for @electorate do |f|
  -if @electorate.errors.any?
    #error_explanation
      %h2= "#{pluralize(@electorate.errors.count, "error")} prohibited this electorate from being saved:"
      %ul
        - @electorate.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :polygon
    = f.text_area :polygon
  .actions
    = f.submit 'Save'

app/views/electorates/edit.html.haml
%h1 Editing electorate

= render 'form'

= link_to 'Show', @electorate
\|
= link_to 'Back', electorates_path

app/views/electorates/index.html.haml
%h1 Listing electorates

.container
	.wood
		.board
			.row
				- @electorates.each_with_index do |electorate, i|
					.span3.offset1.space
						=link_to "#{electorate.title}", electorate_path(electorate.title.downcase)
						=electorate.state

app/views/electorates/new.html.haml
%h1 New electorate

= render 'form'

= link_to 'Back', electorates_path

app/views/electorates/show.html.haml
.container
	.wood
		.board
			.row
				.span4.offset
					.map-container
						#map
				.span7
					%p#notice= notice

					%h1= "#{@electorate.title}, #{@electorate.state}"

					%h2 Representatives (1998-2011)

					- @members.sort{|x,y| x.last_name <=> y.last_name}.each do |m|
						.span2
							.frame
								%image.border{:src => "http://202.2.94.230/images/mpborder.png"}
								%image.portrait{:src => "http://parlinfo.aph.gov.au/parlInfo/download/handbook/allmps/#{m.aphkey}/upload_ref_binary/#{m.aphkey}.JPG"}
							%h3=link_to "#{m.first_name} #{m.last_name}", member_path(m.aphkey)
							%p="(#{m.party})"
							%p="#{m.speeches.last.date.strftime("%m/%Y")} to #{m.speeches.first.date.strftime("%m/%Y")}"